In [3]:
import pandas as pd

#Part A — Understanding Individual Datasets
#1. Load all three CSV files.
customer = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")

In [4]:
#2. Display the dimensions of each DataFrame.
customer.info()
products.info()
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    3000 non-null   object
 1   Customer_Name  3000 non-null   object
 2   City           3000 non-null   object
 3   Age            3000 non-null   int64
 4   Gender         3000 non-null   object
dtypes: int64(1), object(4)
memory usage: 117.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    100 non-null    object
 1   Product_Name  100 non-null    object
 2   Category      100 non-null    object
 3   Price         100 non-null    float64
dtypes: float64(1), object(3)
memory usage: 3.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     15000 non-null  object
 1   Customer_ID  15000 non-null  object
 2   Product_ID   15000 non-null  object
 3   Quantity     15000 non-null  int64
 4   Order_Date   15000 non-null  object
dtypes: int64(1), object(4)
memory usage: 586.1+ KB

In [5]:
print("Customer Columns:", customer.columns.tolist())
print("Products Columns:",  products.columns.tolist())
print("Orders Columns:", orders.columns.tolist())

Customer Columns: ['Customer_ID', 'Customer_Name', 'City', 'Age', 'Gender']
Products Columns: ['Product_ID', 'Product_Name', 'Category', 'Price']
Orders Columns: ['Order_ID', 'Customer_ID', 'Product_ID', 'Quantity', 'Order_Date']

In [6]:
#4. Identify the common columns between datasets.
import numpy as np
# Find common columns
common_cols = list(set.intersection(*map(set, [customer.columns, products.columns, orders.columns])))
print(common_columns)

NameError: name 'common_columns' is not defined

In [ ]:
#5. Determine how the three datasets are related.
# need assistance

In [ ]:
#Part B — Data Cleaning
#6. Check each DataFrame for missing values.
customer.isna().values.any()
products.isna().values.any()
orders.isna().values.any()

In [10]:
#7. Check for duplicate records.
print("Customer duplicates")
customer[customer.duplicated()]
print("Products duplicates")
products[products.duplicated()]
print("Orders duplicates")
orders[orders.duplicated()]

Customer duplicates
Products duplicates
Orders duplicates

Empty DataFrame
Columns: [Order_ID, Customer_ID, Product_ID, Quantity, Order_Date]
Index: []

In [11]:
#8. Check the validity of Customer_ID and Product_ID.
#Need assistance

In [12]:
#9. Convert Order_Date into datetime.
orders["Order_Date"] = pd.to_datetime(orders["Order_Date"])

In [13]:
#10. Check whether every order corresponds to a valid customer.
# Need assistance

In [14]:
#11. Check whether every order corresponds to a valid product.
#Need assistance

In [15]:
#Part C — Combining Data
#12. Merge orders with customers
merged_orders = orders.merge(customer, on="Customer_ID", how="inner")
print(len(merged_orders) == len(orders))

True

In [16]:
#13. Merge the resulting DataFrame with products.
#Need assistance

In [17]:
#14.Create a final consolidated DataFrame.
final_product = merged_orders.merge(products, on="Product_ID", how="inner")
print(final_product)

      Order_ID Customer_ID Product_ID  Quantity          Order_Date  \
0      O000001      C00861      P0027         4 2025-01-01 00:00:00
1      O000002      C01295      P0047         3 2025-01-01 02:00:00
2      O000003      C01131      P0099         4 2025-01-01 04:00:00
3      O000004      C01096      P0006         1 2025-01-01 06:00:00
4      O000005      C01639      P0060         2 2025-01-01 08:00:00
...        ...         ...        ...       ...                 ...
14995  O014996      C01275      P0078         3 2028-06-03 14:00:00
14996  O014997      C00946      P0017         5 2028-06-03 16:00:00
14997  O014998      C02228      P0022         5 2028-06-03 18:00:00
14998  O014999      C00293      P0030         2 2028-06-03 20:00:00
14999  O015000      C00584      P0081         1 2028-06-03 22:00:00

       Customer_Name        City  Age  Gender Product_Name         Category  \
0       Customer_861     Kolkata   51  Female   Product_27           Sports
1      Customer_1295   Bangalore   43    Male   Product_47         Clothing
2      Customer_1131        Pune   47  Female   Product_99      Electronics
3      Customer_1096       Delhi   29    Male    Product_6         Clothing
4      Customer_1639  Coimbatore   67  Female   Product_60           Sports
...              ...         ...  ...     ...          ...              ...
14995  Customer_1275        Pune   22  Female   Product_78         Clothing
14996   Customer_946        Pune   39  Female   Product_17  Home Appliances
14997  Customer_2228  Coimbatore   64  Female   Product_22      Electronics
14998   Customer_293   Hyderabad   69  Female   Product_30            Books
14999   Customer_584   Hyderabad   34  Female   Product_81         Clothing

          Price
0      56171.59
1      80831.23
2      83546.72
3        651.66
4      81819.68
...         ...
14995  28555.57
14996   6449.48
14997  88732.55
14998  52321.01
14999  50317.63

[15000 rows x 12 columns]

In [18]:
#Part D — Business Calculations
#15. Create:
#Order_Value = Price × Quantity
final_product["Order_Value"] = final_product["Price"] * final_product["Quantity"]

In [19]:
#16. Calculate total revenue.
print(f"Total Revenue",sum(final_product["Order_Value"]))

Total Revenue 2233171871.3000107

In [20]:
#17. Calculate average order value.
print(f"average order value",final_product["Order_Value"].mean())

average order value 148878.12475333334

In [21]:
#18. Find total revenue by product category.
print(f"average order value",final_product.groupby("Category")["Order_Value"].mean())

average order value Category
Beauty             117828.356533
Books              177875.412111
Clothing           149736.083700
Electronics        206670.382445
Home Appliances    129065.430023
Sports             144673.756769
Name: Order_Value, dtype: float64

In [22]:
#19. Find total revenue by city.
print(f"total revenue by city",final_product.groupby("City")["Order_Value"].sum())

total revenue by city City
Bangalore     2.637059e+08
Chennai       2.519685e+08
Coimbatore    2.831225e+08
Delhi         2.654541e+08
Hyderabad     2.932639e+08
Kolkata       3.155500e+08
Mumbai        2.803566e+08
Pune          2.797505e+08
Name: Order_Value, dtype: float64

In [23]:
#20. Find the top 10 customers by spending.
customer_filter = final_product.groupby("Customer_Name")["Order_Value"].sum()
print(f"top 10 customers by spending", customer_filter.sort_values(ascending=False).head(10))

top 10 customers by spending Customer_Name
Customer_19      3176078.87
Customer_2897    2528868.53
Customer_1915    2476932.74
Customer_2709    2400905.35
Customer_187     2394078.09
Customer_685     2352464.63
Customer_1297    2345815.39
Customer_259     2330070.43
Customer_921     2257528.60
Customer_271     2226186.64
Name: Order_Value, dtype: float64

In [24]:
#21. Find the top 10 products by revenue.
product_filter = final_product.groupby("Product_Name")["Order_Value"].sum()
print(f"top 10 products by revenue.", product_filter.sort_values(ascending=False).head(10))

top 10 products by revenue. Product_Name
Product_74    47258003.68
Product_88    47213343.92
Product_3     47075130.00
Product_46    45000771.20
Product_52    44990386.56
Product_73    44897635.86
Product_68    44696626.32
Product_38    43658393.09
Product_54    40946977.89
Product_50    40756127.88
Name: Order_Value, dtype: float64

In [25]:
#22. Find the most frequently purchased product.
product_filter = final_product["Product_Name"].value_counts()
print(product_filter.sort_values(ascending=False).head(1))

Product_Name
Product_15    183
Name: count, dtype: int64

In [26]:
#23. Find the city with the highest number of customers.
city_filter = final_product["City"].value_counts()
print(city_filter.sort_values(ascending=False).head(1))

City
Kolkata    2057
Name: count, dtype: int64

In [27]:
#24. Find the city generating the highest revenue.
citywiserevenue = final_product.groupby("City")["Order_Value"].sum()
print("the city generating the highest revenue", citywiserevenue.sort_values( ascending=False).head(1))

the city generating the highest revenue City
Kolkata    3.155500e+08
Name: Order_Value, dtype: float64

In [28]:
#Part E — Customer Analysis
#25. Divide customers into age groups.
#18–30
#31–45
#46–60
#61+
final_product["Age_Group"] = final_product["Age"].apply(lambda x : "Senior Citizen" if x >= 61
                                                        else "Adult" if x >= 46 and x <= 60
                                                        else "Senior Youth" if x>=31 and x<=45
                                                        else "Youth" if x>= 18 and x<=30
                                                        else "Child")
print(final_product)

      Order_ID Customer_ID Product_ID  Quantity          Order_Date  \
0      O000001      C00861      P0027         4 2025-01-01 00:00:00
1      O000002      C01295      P0047         3 2025-01-01 02:00:00
2      O000003      C01131      P0099         4 2025-01-01 04:00:00
3      O000004      C01096      P0006         1 2025-01-01 06:00:00
4      O000005      C01639      P0060         2 2025-01-01 08:00:00
...        ...         ...        ...       ...                 ...
14995  O014996      C01275      P0078         3 2028-06-03 14:00:00
14996  O014997      C00946      P0017         5 2028-06-03 16:00:00
14997  O014998      C02228      P0022         5 2028-06-03 18:00:00
14998  O014999      C00293      P0030         2 2028-06-03 20:00:00
14999  O015000      C00584      P0081         1 2028-06-03 22:00:00

       Customer_Name        City  Age  Gender Product_Name         Category  \
0       Customer_861     Kolkata   51  Female   Product_27           Sports
1      Customer_1295   Bangalore   43    Male   Product_47         Clothing
2      Customer_1131        Pune   47  Female   Product_99      Electronics
3      Customer_1096       Delhi   29    Male    Product_6         Clothing
4      Customer_1639  Coimbatore   67  Female   Product_60           Sports
...              ...         ...  ...     ...          ...              ...
14995  Customer_1275        Pune   22  Female   Product_78         Clothing
14996   Customer_946        Pune   39  Female   Product_17  Home Appliances
14997  Customer_2228  Coimbatore   64  Female   Product_22      Electronics
14998   Customer_293   Hyderabad   69  Female   Product_30            Books
14999   Customer_584   Hyderabad   34  Female   Product_81         Clothing

          Price  Order_Value       Age_Group
0      56171.59    224686.36           Adult
1      80831.23    242493.69    Senior Youth
2      83546.72    334186.88           Adult
3        651.66       651.66           Youth
4      81819.68    163639.36  Senior Citizen
...         ...          ...             ...
14995  28555.57     85666.71           Youth
14996   6449.48     32247.40    Senior Youth
14997  88732.55    443662.75  Senior Citizen
14998  52321.01    104642.02  Senior Citizen
14999  50317.63     50317.63    Senior Youth

[15000 rows x 14 columns]

In [29]:
#26. Calculate revenue generated by each age group.
final_product.groupby("Age_Group")["Order_Value"].sum()

Age_Group
Adult             6.599237e+08
Senior Citizen    3.922680e+08
Senior Youth      6.223524e+08
Youth             5.586278e+08
Name: Order_Value, dtype: float64

In [30]:
#27. Compare spending between male and female customers.
final_product.groupby("Gender")["Order_Value"].sum()

Gender
Female    1.078972e+09
Male      1.154200e+09
Name: Order_Value, dtype: float64

In [31]:
#28. Identify high-value customers.
highvaluecustomers = final_product.groupby("Customer_Name")["Order_Value"].sum()
print(f"High value customer", highvaluecustomers.sort_values(ascending = False).head(1))

High value customer Customer_Name
Customer_19    3176078.87
Name: Order_Value, dtype: float64

In [42]:
#29. Determine the percentage of customers who have placed more than one order.
customersordercount =  final_product.groupby("Customer_ID")["Order_ID"].count()
percentage = (customersordercount > 1).mean() * 100
print(percentage)

96.80779569892472

In [53]:
#Part F — Advanced Analysis
#30. Create a customer spending ranking.
customersspending = final_product.groupby("Customer_Name")["Order_Value"].sum()
print(customersspending.sort_values(ascending=False))

Customer_Name
Customer_19      3176078.87
Customer_2897    2528868.53
Customer_1915    2476932.74
Customer_2709    2400905.35
Customer_187     2394078.09
                    ...
Customer_264        7497.06
Customer_879        4561.62
Customer_577        2606.64
Customer_2035       2383.56
Customer_1558       1954.98
Name: Order_Value, Length: 2976, dtype: float64

In [56]:
#31. Identify the top 10% of customers based on total spending.
print(customersspending.sort_values(ascending=False).head(int(len(customersspending)*0.1)))

Customer_Name
Customer_19      3176078.87
Customer_2897    2528868.53
Customer_1915    2476932.74
Customer_2709    2400905.35
Customer_187     2394078.09
                    ...
Customer_1044    1344617.29
Customer_465     1344033.24
Customer_363     1343700.29
Customer_2198    1343095.17
Customer_1791    1340820.69
Name: Order_Value, Length: 297, dtype: float64

In [60]:
#32. Find the most profitable product category for each city.
final_product.groupby(["City","Category"])["Order_Value"].sum()

City        Category
Bangalore   Beauty             25751474.66
            Books              37954952.93
            Clothing           49814706.84
            Electronics        37175907.13
            Home Appliances    41682040.21
            Sports             71326795.18
Chennai     Beauty             31963920.82
            Books              29771426.80
            Clothing           48476479.58
            Electronics        40376068.07
            Home Appliances    33082498.75
            Sports             68298118.24
Coimbatore  Beauty             40922382.61
            Books              37344682.88
            Clothing           51390608.21
            Electronics        40257614.49
            Home Appliances    43654134.24
            Sports             69553033.93
Delhi       Beauty             37538636.48
            Books              37766566.78
            Clothing           53270825.29
            Electronics        33933237.41
            Home Appliances    41925267.49
            Sports             61019537.25
Hyderabad   Beauty             44100294.55
            Books              41988733.03
            Clothing           55712112.24
            Electronics        44306843.04
            Home Appliances    41439270.44
            Sports             65716665.57
Kolkata     Beauty             41195852.40
            Books              43038066.82
            Clothing           62310387.11
            Electronics        47199208.27
            Home Appliances    49983541.01
            Sports             71822933.47
Mumbai      Beauty             38908783.89
            Books              40150018.05
            Clothing           52669708.16
            Electronics        44496758.34
            Home Appliances    40233093.41
            Sports             63898188.25
Pune        Beauty             36310456.34
            Books              37041884.48
            Clothing           52504066.78
            Electronics        43546986.31
            Home Appliances    39311113.32
            Sports             71035989.75
Name: Order_Value, dtype: float64

In [62]:
#33. Find the most popular product in each category.
final_product.groupby(["Category","Product_Name"])["Order_Value"].sum()

Category  Product_Name
Beauty    Product_10      39423604.01
          Product_100     15590776.05
          Product_14      38414193.35
          Product_2        3139805.76
          Product_21      29535691.37
                             ...
Sports    Product_83      11370269.46
          Product_86       6923125.00
          Product_95      29482585.10
          Product_96      32899212.78
          Product_97      25632219.42
Name: Order_Value, Length: 100, dtype: float64

In [65]:
#34. Calculate monthly revenue.
# 1. Convert the date column to standard datetime format
final_product['date'] = pd.to_datetime(final_product['Order_Date'])

# 2. Extract the year and month period (YYYY-MM)
final_product['month'] = final_product['date'].dt.to_period('M')

# 3. Group by the monthly period and sum the revenue column
monthly_revenue = final_product.groupby('month')['Order_Value'].sum().reset_index()
print(monthly_revenue)

      month  Order_Value
0   2025-01  53361220.93
1   2025-02  52963079.79
2   2025-03  56233288.12
3   2025-04  50923849.46
4   2025-05  57301343.61
5   2025-06  56460489.60
6   2025-07  54157148.69
7   2025-08  57144165.05
8   2025-09  53352193.95
9   2025-10  56630127.31
10  2025-11  59276825.16
11  2025-12  59630660.46
12  2026-01  56260151.26
13  2026-02  47689351.93
14  2026-03  55497703.15
15  2026-04  51306881.32
16  2026-05  51823753.71
17  2026-06  51618514.74
18  2026-07  54128777.26
19  2026-08  57438462.80
20  2026-09  55460907.01
21  2026-10  57171177.74
22  2026-11  56875351.32
23  2026-12  52435333.48
24  2027-01  56072466.01
25  2027-02  48032412.73
26  2027-03  51740476.06
27  2027-04  51673329.49
28  2027-05  55972559.14
29  2027-06  55791489.47
30  2027-07  57720544.86
31  2027-08  55334425.53
32  2027-09  53134726.53
33  2027-10  53646489.78
34  2027-11  53680865.96
35  2027-12  55292934.52
36  2028-01  52205366.58
37  2028-02  48474671.11
38  2028-03  55381632.73
39  2028-04  51636778.77
40  2028-05  57204319.10
41  2028-06   5035625.08

In [67]:
#35. Identify the month with the highest revenue.
monthly_revenue.sort_values(by="Order_Value",ascending=False).head(1)

      month  Order_Value
11  2025-12  59630660.46